---
title: "Lab 5"
author: "Guang Yi Lim"
date: "April 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl)
acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)
person <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)
```
<br/>Part 1
```{r}
ggplot(acc,aes(x = DAY_WEEK)) +geom_histogram(binwidth = .5) + scale_x_continuous(breaks = seq(1,7,1));
#looking at the graph, we can see that accidents happen most frequently on sudays
ggplot(acc %>%filter (HOUR <24),aes(x= HOUR)) +geom_histogram(binwidth = .5)+scale_x_continuous(breaks = seq(0,23,2))
#looking at the graph, accidents tend to happen more frequently during the evening, with 1800 being the peak 
nrow(acc %>% filter(DRUNK_DR >=1))
#we know that there are 8769 incidents involving drunk drivers
```
<br/>Part 2
```{r}
driver <- person %>% filter(PER_TYP==1)

joint <- inner_join(acc,driver,by='ST_CASE')
str(joint)
ggplot(joint,aes(x= DAY_WEEK)) +geom_histogram(binwidth = .5);

ggplot(joint %>% filter(HOUR.x != 99),aes(x= HOUR.y)) +geom_histogram(binwidth = .5)+scale_x_continuous(breaks = seq(0,22,2));

ggplot(joint %>% filter(SEX <3),aes(x= SEX)) +geom_histogram(binwidth = 1)+scale_x_continuous(breaks = seq(1,2,1));
```
<br/>Part 3
```{r}
county <- read_xlsx("FRPP GLC United States.xlsx",skip =1)

colnames(county)[colnames(county)=='County Code'] <- 'COUNTY'
county$COUNTY <- as.numeric(county$COUNTY)

colnames(county)[colnames(county)=='City Code'] <- 'CITY'
county$CITY <- as.numeric(county$CITY)

colnames(county)[colnames(county)=='State Code'] <- 'STATE'
county$STATE <- as.numeric(county$STATE)

acc1<- acc %>%select(`ST_CASE`,COUNTY,CITY,STATE)
join1 <- acc1 %>% left_join(county,by = c('COUNTY','CITY','STATE'))
join1 = join1 %>% mutate(`County Name` = tolower(`County Name`))
join2 = join1 %>% group_by(`County Name`) %>% summarize(total_crashes= n())
countyMap <- map_data("county")
names(countyMap)[6] = "County Name"
final =countyMap %>% left_join(join2, by="County Name")
final[is.na(final)] <- 0

final %>% ggplot(aes(x=long,y=lat,fill = total_crashes)) +geom_polygon(aes(group = group)) +scale_fill_continuous(low='pink',high ='blue')


```
