---
title: "team"
author: "Colin Brown and Guang Lim"
date: "April 18, 2019"
output: html_document
---
```{r}
acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)

names(acc)
```

```{r}
#PART ONE
library(dplyr)
library(ggplot2)
library(stringr)
library(readxl)
str(acc$DAY_WEEK)
acc$DAY_WEEK <- as.character(acc$DAY_WEEK)
labeled_days <- acc$DAY_WEEK %>% 
  str_replace_all('1', "Sunday") %>%
  str_replace_all('2', "Monday") %>%
  str_replace_all('3', "Tuesday") %>%
  str_replace_all('4', "Wednesday") %>%
  str_replace_all('5', "Thursday") %>%
  str_replace_all('6', "Friday") %>%
  str_replace_all('7', "Saturday")

acc$DAY_WEEK <- labeled_days
acc$DAY_WEEK <- as.factor(acc$DAY_WEEK)
acc$DAY_WEEK <- factor(acc$DAY_WEEK, levels=c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
ggplot(acc, aes(x=DAY_WEEK)) + geom_bar() + xlab("Day of the Week") + ylab("Accidents") + ggtitle("Accidents per Day of the Week")
# Saturday has the most accidents, followed by Sunday

ggplot(acc %>%filter (HOUR <24),aes(x= HOUR)) +geom_bar()+scale_x_continuous(breaks = seq(0,23,1)) + ylab("Accidents") + ggtitle("Car Accidents by Time of Day")
# Looking at the chart, most accidents tend to happen in the evening, with the most accidents happening at hour 18, or 6:00pm.

count <- 0
for(i in acc$DRUNK_DR){
  if(i != 0){
    count <- count + 1
  }
}
count
# There were 8769 accidents involving a drunk driver.

```

```{r}
# PART 2
person <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv")

drivers <- subset(person, person$PER_TYP==1)

combined <- full_join(acc, drivers, by="ST_CASE")

combined$SEX <- as.factor(combined$SEX)
labeled_sex <- combined$SEX %>%
  str_replace_all('1', "Male") %>%
  str_replace_all('2', "Female")

combined$SEX <- labeled_sex

table(combined$SEX)
# The table output shows that there are more accidents involving male drivers than female drivers

ggplot(data=subset(combined, combined$HOUR.x != 99 & combined$SEX != 8 & combined$SEX != 9), aes(x=HOUR.x, fill=SEX)) + geom_bar() + facet_wrap(~DAY_WEEK) + xlab("Hour of the Day") + ylab("Accidents") + ggtitle("Accidents by Hour and Sex Across Days of the Week")
```

```{r}
# PART 3
county <- read_xlsx("FRPP GLC United States.xlsx",skip =1)

colnames(county)[colnames(county)=='County Code'] <- 'COUNTY'
county$COUNTY <- as.numeric(county$COUNTY)

colnames(county)[colnames(county)=='City Code'] <- 'CITY'
county$CITY <- as.numeric(county$CITY)

colnames(county)[colnames(county)=='State Code'] <- 'STATE'
county$STATE <- as.numeric(county$STATE)

acc1<- acc %>%select(`ST_CASE`,COUNTY,CITY,STATE)
join1 <- acc1 %>% left_join(county,by = c('COUNTY','CITY','STATE'))
join1 = join1 %>% mutate(`County Name` = tolower(`County Name`))
join2 = join1 %>% group_by(`County Name`) %>% summarize(total_crashes= n())
countyMap <- map_data("county")
names(countyMap)[6] = "County Name"
final =countyMap %>% left_join(join2, by="County Name")
final[is.na(final)] <- 0

final %>% ggplot(aes(x=long,y=lat,fill = total_crashes)) +geom_polygon(aes(group = group)) +scale_fill_continuous(low='pink',high ='blue') + xlab("Longitude") + ylab("Latitude") + ggtitle("Car Accidents in the U.S. by County")



```